describe("magaz pay", function() {

      it("visit", function() {
        cy.clearCookies()
        cy.clearLocalStorage()
        cy.visit("https://magaz.apgrup.ru")

        cy.get('._2S9w')
          .click()
        cy.get('._3HZ_')
          .click()
        cy.get('._1rlq')
          .contains('Audi')
          .should('be.visible')
          .click()
        cy.get('._2OVU')
          .contains('Купить')
          .click()
        cy.get('._2K0Z')
          .contains('Товар успешно добавлен')
          .should('be.visible')
        cy.get('.exzB > :nth-child(2) > ._2sMB')
          .contains('Перейти в корзину')
          .click()
        cy.get('._1rlq')
          .contains('Корзина')
          .should('be.visible')
        cy.get('._28dd > ._2sMB')
          .contains('Оформить заказ')
          .click()
        cy.get('._1rlq')
          .contains('Химический переулок, дом 1, литер АЦ')
          .should('be.visible')
        cy.get('._1Y2L > ._2sMB')
          .contains('Забрать отсюда')
          .click()
        cy.get('._11Gk > :nth-child(1) > :nth-child(1)')
          .contains('Артикул')
          .should('be.visible')
        cy.get('._3zZ- > ._2sMB')
          .contains('Отправить смс')
          .click()
        cy.get('._3vPm > ._1z4-')
          .contains('Введите')
          .should('be.visible')
        cy.get('._3vPm > ._1z4- > ._1kfX > ._2WYl')
          .click( {force:true} )
          .clear()
          .type('1234567890')
          .should('value', '+7 (123) 456-78-90')
        cy.get('#root > div > div.TjJL > div._11Gk > div > div > form > div._3vPm > div._3zZ-')
          .contains('Отправить смс')
          .click( {force:true} )
        cy.wait(2000)
        cy.get('#root > div > div.TjJL > div._11Gk > div > div > form > div._3vPm > div._1z4- > label > input')
          .click( {force:true} )
          .type('123456')
        cy.get('#root > div > div.TjJL > div._11Gk > div > div > form > div:nth-child(4) > label > label > svg')
          .click( {force:true} )
        cy.get('#root > div > div.TjJL > div._11Gk > div > div > form > div:nth-child(4) > button')
          .contains('Подтвердить заказ')
          .click( {force:true} )
        cy.get('#root > div')
          .contains('Спасибо за ваш заказ!')
          .should('be.visible')
        cy.get('._25tR > ._2sMB')
          .click();
        cy.get('.pay-container')
          .contains('Яндекс')
          .click();
        cy.get('#pay-form-submit')
          .contains('Продолжить')
          .click();
        cy.get('.page-wrapper')
          .contains('Эмулировать оплату')
          .click();
});
});
